# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "About me"
#  url = "#about"
#  weight = 10

#[[main]]
#name = "New"
#url = "#featured"
#weight = 10

[[main]]
  name = "BLOG"
  url = "/post/"
  weight = 15

  
[[main]]
 name = "PROJECTS"
  url = "/projects"
  weight = 20
  
[[main]]
 name = "Quick SOLVES"
  url = "/publication"
  weight = 20
  
  
[[main]]
  name = "ABOUT ME"
  url = "/Bio/"
  weight = 30


#[[main]]
#  name = "Cubing"
#  url = "/talk"
#  weight = 50

[[main]]
  name = "CONTACT"
  url = "/Contact"
  weight = 60

#Link to a PDF of your resume/CV from the menu.
#To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 70
