---
title: I will start teaching
authors: 
  - admin
date: '2020-07-20'
categories:
  - Blog
  - Teaching
tags:
  - Python
  - Academia Desafio Latam
image:
  caption: ""
  focal_point: "Top"
summary: "I will start teaching Python at Academia Desafio Latam"
highlight: true
math: true
output:
  blogdown::html_page:
    toc: false
    number_sections: false
    toc_depth: 4
    fig_caption: yes
    
---

## Academia Desafio Latam

Because of Coronavirus pandemic I started to look for opportunities. I'm not sure if it is the right moment to do it, but I found the opportunity to start teaching Python and I took it. I applied with no hopes, and I received a reply message sharing the Data Science program syllabus plus an invitation to a technical interview.

I won't spoil the interview, but I found it so difficult. Not even in my previous or current job had such a comprehensive interview. Here in Chile, technical interviews are not very deep. I think this is mainly because recruiters or even technical leaders are not very specialized in technical aspects but focused into management. 

So in my case I had 47 questions that needed to be responded live explaining concepts regarding Python, Statistics and Machine Learning. I think I was well prepared for the interview, but I got surprised of the results. I did very good at the interview, so recruiters asked me to prepare a simulated class. I prepared a Naive Bayes Model and I had to explain some of the theory behind, show examples on how the algorithm works and some other concepts regarding GAM models (I had to learn about those because I have never fitted one). Again I did well in the simulated class and today is my first day. I will try to share of the experience teaching and showcase problems that may come up when dealing with their projects. 

I'm super excited, I've always wanted to teach Data Science in a formal Institution. And without even getting started I have to say the following things:

* I was really impressed about the program, if you are in Chile you can learn more [here](https://desafiolatam.com/data-science/).
* It considers Python, Statistics, Machine Learning, SQL and databases and some Big Data Frameworks. It also includes a final Capstone Project.
* It's focused on implementation in Python which is nice. A lot of theory will be covered but it is also really hands-on.
* The requirements to apply are not very high, and this could be deceptive because the level in the program is quite important.
* I had the chance to see the final Capstone Project Presentations and I was really impressed with the results. That is why I feel enthusiastic about the program. I really liked the results, students had to create a presentation plus designing and App with a model that solves an specific problem. In their presentations stakeholders of related fields were able to watch the results and establish job opportunities and commercial deals about the product they prototyped.

So this is it. I will be sharing more experiences, so Stay Tuned!!





