---
title: Latin R
authors: 
  - admin
date: '2019-09-24'
categories:
  - Vapire Diaries
  - Rambling
tags:
  - R
  - Conference
image:
  caption: ""
  focal_point: "Top"
summary: "Hadley is coming to Chile and I´ll be taking some Package Development Classes with him"
highlight: true
math: true
output:
  blogdown::html_page:
    toc: false
    number_sections: false
    toc_depth: 4
    fig_caption: yes
    
---

## Latin R

Latin R is a conference organized by RLadies Latam and is the oportunity we have here in Chile to get acquainted about the last R breakthrough and how is being using in Research, companies, etc.
They also provide a full day of Tutorials and of course important keynotes are invited to come over. This year I think is huge, because 3 Main R users are coming:

### Mine Çetinkaya-Rundel

She is one of the most important persons involved into R Teaching. Statistics Professor from Duke University. I personally had the chance to take some Coursera and Datacamp Courses with her and I learned a lot, really good teacher and really knowledgable. Having her now here in Chile to meet her in person is such a great Honor. I just can´t wait to hear about what she has to say.
She will be conducting a Tutorial on how to Teach R and of Course a main Speech.

### Erin Ledell

I have to say I don't know a lot about her but she has a great curriculum: Chief Machine Learning Scientist at H2O, co-founder of Rladies Global and Woman+ in ML/DS, plus BioStatistics Phd at Berkeley, that is more than enough. She will be conducting a Tutorial on Machine Learning and Deep Learning that of course I´ll be taking so I´ll give more details on a later post.

### Hadley Wickham
This Guy needs no Introduction. He is the Chief Scientist at RStudio and he will be giving the Main Speech of the Conference plus a Package Development Tutorial. Of ourse I will be in first row of this Tutorial and I expect to learn a lot and have a lot of questions prepared beforehand.

This guys is by far my most important inspiration when it comes to working in R. Definitely this guy has made my life way easier because of all of the packages that he has created and I use almost every day.

I'll be the next 3 days in the Conference and I expect to share some pictures and experiences about the things I will learn.

Stay tuned!!!